import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import os

class SpotifyClient:
    _instance = None
    _playlist_id = None
    _user_id = '31voublfb2go4ti7iror54t2cbai'

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(SpotifyClient, cls).__new__(cls)
            client_id=os.getenv('CLIENT_ID')
            client_secret=os.getenv('CLIENT_SECRET')
            client_credentials_manager = SpotifyClientCredentials(client_id, client_secret)
            if not client_id or not client_secret:
                raise ValueError("Missing client id or client secret from env variables.")
            
            cls._instance._client = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

        return cls._instance
        
    def get_client(self):
        return self._client

    def create_playlist(self):
        playlist_data = self._client.user_playlist_create(user=self._user_id, name='oooo beach', public=False, description='playlist generated by flowify')
        self._playlist_id = playlist_data['id']

    def add_songs_to_playlist(self, song_to_artists):
        track_uris = []
        for song, artists in song_to_artists.items():
            combined_artists = '%'.join(artists)
            track_data = self._client.search(q = f'{song}%{combined_artists}', type='track')
            print('track data', track_data)
            track_uri = track_data['items'][0]['uri']
            track_uris.append(track_uri)

        self._client.user_playlist_add_tracks(user=self._user_id, playlist_id=self._playlist_id, tracks=track_uris)

        
        
    

